### ISSUE TITLE
MapUserTrackingMode.follow is Ambiguous

### ISSUE THREAD

**Issue by rderimay** [pauljohanneskraft/Map#12]
Hi there and thanks for the good work! 

when writing the following:
`@State private var userTrackingMode = MapUserTrackingMode.follow`

I get the following error: `Ambiguous use of 'follow'`

Hope not to bother you with typical newbie stupid stuff, but cannot find a way to go around this...

**Comment by pauljohanneskraft** [comment]
Hey - thank you very much for your kind words. No worries about asking questions.

I think the issue here is that you are either importing both MapKit and Map in the file this error occurs or neither. If you require both imports, you can use a `Map.` prefix to differentiate between the two different values from the two frameworks. In this case, it might make sense to change the line above to `@State private var userTrackingMode = Map.MapUserTrackingMode.follow`

**Comment by pauljohanneskraft** [comment]
Okay, this is happening due to a name clash of the Map-struct inside the Map module and the Map module 😓 

One workaround would be to use a custom name in your model for this one file - just for now - I will try to find a solution to this - probably by renaming `MapUserTrackingMode` to `UserTrackingMode` or getting rid of it altogether and using the MapKit one directly.

That additional file would only be the following:

```swift
import Map

typealias UserTrackingMode = MapUserTrackingMode
```

Then in your existing file, replace all usages of `MapUserTrackingMode` with `UserTrackingMode`

**Comment by rderimay** [comment]
Yes this works, thanks!

**Comment by rderimay** [comment]
Ah ah. No it does not.

I get this now:
![Screen 2022-06-28 à 12 01 27](https://user-images.githubusercontent.com/12871929/176188824-78131d5c-8ffa-4619-9b7d-5b55957ae31a.png)

and this is directly connected to setting `userTrackingMode: $userTrackingMode` with `@State private var userTrackingMode: UserTrackingMode = .follow`

**Comment by pauljohanneskraft** [comment]
Yes, it is because it automatically sets `showsUserLocation` to `true`, which is then creating an annotation for that user location. Please simply update your package version and this assertion should be gone.

**Comment by rderimay** [comment]
Switching to main instead of 0.1.0 does indeed solve the problem :-) Thanks!

**Comment by pauljohanneskraft** [comment]
Hey @rderimay ! I have just opened a new PR #16 which changes the type of the userTrackingMode to the previous MapKit MKUserTrackingMode value instead of creating a new custom type for this.

What do you think about this change?
