### ISSUE TITLE
Map Annotation selection

### ISSUE THREAD

**Issue by vx8** [pauljohanneskraft/Map#17]
Hello @pauljohanneskraft , loving your library!

Is there a way to support annotation selection? I already tried with navigationLinks and tapGestures with no luck 

Thanks

**Comment by pauljohanneskraft** [comment]
Hey - thank you 😊 

Unfortunately, there is no such feature at the moment and I'm still not quite sure how it could be reasonably implemented.

What would you think about a solution where you can put in a `Binding<Set<AnnotationItem.ID>>` or `Binding<Array<AnnotationItem>>` to select and deselect annotations? When these annotations are deselected by the user, they are removed from the array/set again. More information about this will be tracked in #4.

Or are you talking about being able to tap on them and then performing some action? You could theoretically do that with a button, but for some reason MKAnnotationView apparently does not forward user interaction to its children. I'm currently working on this (as described in #11) and have a version that sometimes accepts button taps, but unfortunately, it stops working after some time.

Since in both cases this would be a duplicate issue, I will close this one. If your question does not fit into either of these issues, let me know and I will reopen this.
